= Installing the WFDB Software Package

This appendix briefly describes how to install the WFDB Software Package
on a new system.  The package includes C-language sources for the WFDB
library and for most of the applications described in this manual, sources
for this manual, the _WFDB Programmer's Guide_, and the
_WAVE User's Guide_, and a one-minute sample record (`100s`).

The latest version of the package can always be downloaded in source form
from https://physionet.org/[PhysioNet].

== Prerequisites

Install the required development tools and optional dependencies for your
platform:

.Debian / Ubuntu
----
sudo apt-get install gcc meson ninja-build libflac-dev libcurl4-gnutls-dev
----

.Fedora / RHEL
----
sudo dnf install gcc meson ninja-build flac-devel libcurl-devel
----

For WAVE (the waveform viewer), you also need GTK 3 and VTE:

.Debian / Ubuntu
----
sudo apt-get install libgtk-3-dev libvte-2.91-dev
----

.Fedora / RHEL
----
sudo dnf install gtk3-devel vte291-devel
----

== Building and Installing

The WFDB Software Package uses the https://mesonbuild.com/[Meson] build
system.

. *Configure the build:*
+
----
meson setup build --prefix=/usr/local
----
+
Use `--prefix` to choose the installation directory.  For a local
(non-root) installation, use something like:
+
----
meson setup build --prefix=$HOME/wfdb
----

. *Build:*
+
----
ninja -C build
----

. *Run the test suite* to verify the build:
+
----
meson test -C build
----

. *Install:*
+
----
ninja -C build install
----

== Build Options

Meson options can be set with `-Doption=value` during `meson setup`:

[cols="1,1,3"]
|===
|Option |Default |Description

|`netfiles`
|`auto`
|HTTP/FTP file access via libcurl

|`flac`
|`auto`
|FLAC signal compression support

|`wave`
|`auto`
|WAVE waveform viewer (requires GTK 3 and VTE)

|`dbdir`
|`<datadir>/wfdb`
|Database directory
|===

For example, to disable network file support:

----
meson setup build -Dnetfiles=disabled
----

*Important:* Although you may be able to compile the WFDB Software Package
using a proprietary compiler, this is _not supported_.
